<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DokumenSakipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dokumen = [
            // Kategori: Pedoman & Ketentuan
            [
                'kategori' => 'pedoman_ketentuan',
                'judul' => 'Pedoman JA Nomor 4 Tahun 2025 tentang Evaluasi Akuntabilitas Kinerja Instansi Pemerintah di Lingkungan Kejaksaan Republik Indonesia.pdf',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/file/d/1Hm8d_Cvk_h9aA8rIYb1XyJO6C1WTwjAs/view',
                'icon' => 'bi-file-earmark-pdf-fill text-danger',
                'urutan' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'pedoman_ketentuan',
                'judul' => 'PEDOMAN JA NOMOR 4 TAHUN 2024_PENYELENGGARAAN SAKIP',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/file/d/1mNb9htgVw1ClP_0eHWAwBjYp6ygIG9-m/view?usp=drive_link',
                'icon' => 'bi-file-earmark-pdf-fill text-danger',
                'urutan' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'pedoman_ketentuan',
                'judul' => 'Peraturan SAKIP',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/u/0/folders/1lRlkVrXcECSfNdzoGpPpsftYrWHN2ddn',
                'icon' => 'bi-folder-fill text-warning',
                'urutan' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Kategori: Template Dokumen SAKIP Tahun 2026
            [
                'kategori' => 'template_tahun_berjalan',
                'judul' => 'FORMAT RENCANA AKSI KINERJA DAN LAPORAN MONEV RENAKSI KINERJA ES I TW I 2026',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/16jJkdH1mW-h4CSKQn2Jgg4suwG86ocvg?usp=drive_link',
                'icon' => 'bi-file-earmark-text-fill text-primary',
                'urutan' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'template_tahun_berjalan',
                'judul' => 'LKJ TW I Tahun 2026 - KEJATI, KEJARI DAN CABJARI',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1e-f1ElSCYFGOPQvvxti3Je0q_vnpCFY8?usp=sharing',
                'icon' => 'bi-file-earmark-bar-graph text-info',
                'urutan' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'template_tahun_berjalan',
                'judul' => 'Rencana Aksi Kinerja Tahun 2026',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1gldPqRO1rTIbeNY8P5eEarnhl1b_PypE?usp=sharing',
                'icon' => 'bi-calendar-event text-warning',
                'urutan' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'template_tahun_berjalan',
                'judul' => 'Monev Renaksi Kinerja TW I Tahun 2026',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1lzttjDxiYNoAKSS0ZNCFbLZIpQ-SuA89?usp=sharing',
                'icon' => 'bi-clipboard2-data text-success',
                'urutan' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'template_tahun_berjalan',
                'judul' => 'RASTAFF EKA Tahun 2026',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1I6UQ5UizAHDwAL8UPcq9Oqo9SHo7rUtX?usp=sharing',
                'icon' => 'bi-people-fill text-secondary',
                'urutan' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kategori: Template Dokumen SAKIP Tahun 2025 (Arsip)
            [
                'kategori' => 'arsip_template',
                'judul' => 'Template LKjIP Satuan Kerja Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1bAzTx5kaIJvP8jnAA5RZqGGA5hWxbevR?usp=sharing',
                'icon' => 'bi-file-earmark-word text-primary',
                'urutan' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Cover LKjIP Satuan Kerja Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1_9_N5Ax5eIhLIUTYG3_4L6pZgqm9uKR_?usp=sharing',
                'icon' => 'bi-image text-success',
                'urutan' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Template LKJ Triwulan III Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://docs.google.com/document/d/14HkvvEJmGyPo0QfhPElCxwVhC5Ri6q2s/edit?usp=sharing&ouid=109556050232324402632&rtpof=true&sd=true',
                'icon' => 'bi-file-earmark-text text-info',
                'urutan' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Pohon Kinerja Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1WdulmYbNpOzFCCathQhJ1W_7IVwdFOHi?usp=drive_link',
                'icon' => 'bi-diagram-2 text-success',
                'urutan' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Format Rencana Aksi Kinerja Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1Do5DZKQI-mNWfpT9jpMs0Tp8zOx7BD3d?usp=sharing',
                'icon' => 'bi-calendar-event text-warning',
                'urutan' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Format Laporan Monev Rencana Aksi Kinerja Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1uHlIHeS44wRVsPBWiY0sOG7Ha5TFerP1?usp=sharing',
                'icon' => 'bi-clipboard2-data text-primary',
                'urutan' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'IKU / Penetapan Target Kinerja 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1KlMJCKb8mmDlvPiYkjkuWNXyrRsQtfMB?usp=sharing',
                'icon' => 'bi-bullseye text-danger',
                'urutan' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Rencana Kerja Kejaksaan RI Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/file/d/1xxiHanwuk8Cpqn2i9noXKGiCO3iSSKMy/view?usp=sharing',
                'icon' => 'bi-file-earmark-pdf text-danger',
                'urutan' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'FORMAT RANWAL RENSTRA (SATKER DAERAH) - Google Drive',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1_9fQmMKStFHbmFHQ9wQSrJu_1hIk04YL?usp=sharing',
                'icon' => 'bi-folder text-warning',
                'urutan' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'PK 2025 RANWAL ESELON III KEJATI - Google Drive',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1Vvw2zC17nN3Q7KqWiHy4WrxSatIm68_O?usp=sharing',
                'icon' => 'bi-folder text-warning',
                'urutan' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'PK 2025 RANWAL ESELON IV KEJARI - Google Drive',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1fFETnMV0DSH0Bpo8sv1A8HMfoJ8evO9i?usp=sharing',
                'icon' => 'bi-folder text-warning',
                'urutan' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'PK 2025 RANWAL ESELON V CABJARI - Google Drive',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1UuRUanPDHpQu-rcfiwS7lWSVyuvT4lhW?usp=sharing',
                'icon' => 'bi-folder text-warning',
                'urutan' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'PK 2025 RANWAL ESELON PEJABAT STRUKTURAL LAINNYA - Google Drive',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1AlxsuXxMVW9FDCJWhUjrovXsHoMQ3eFP?usp=sharing',
                'icon' => 'bi-folder text-warning',
                'urutan' => 13,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Template LKJ Triwulan II Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://docs.google.com/document/d/15oy4mfmFbGb81Bnwz5PPpXs1zN_anokd/edit?usp=sharing&ouid=109556050232324402632&rtpof=true&sd=true',
                'icon' => 'bi-file-earmark-text text-info',
                'urutan' => 14,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Template LKJ Triwulan I Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/u/0/folders/1JAD4l9KZA7d4ANKmexS3rrID3DrPekD1',
                'icon' => 'bi-folder text-warning',
                'urutan' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Template RAPAT STAFF EKA Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://docs.google.com/document/d/12waQaX6lK8NjGzHBCk5fOaetXSzEcwxe/edit?usp=sharing&ouid=109556050232324402632&rtpof=true&sd=true',
                'icon' => 'bi-file-earmark-text text-info',
                'urutan' => 16,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori' => 'arsip_template',
                'judul' => 'Template PK Ranwal_Kasatker Tahun 2025',
                'deskripsi' => null,
                'url' => 'https://drive.google.com/drive/folders/1sDIeMaE1gnVn3pkyI5qBcOaEv_qg8h1f?usp=drive_link',
                'icon' => 'bi-folder text-warning',
                'urutan' => 17,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('dokumen_sakips')->insert($dokumen);
    }
}
